# Generated by Django 2.1.4 on 2019-03-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='unit_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
